services:
  # Backend FastAPI
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5600:5600"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - backend
    restart: unless-stopped

  # Redis (optional for caching and session management)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: