services:
  # Backend FastAPI
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URI=mssql+pyodbc://financeiro:BlomaqFinanceiro$$@54.232.194.197:1433/Locador_2?driver=ODBC+Driver+17+for+SQL+Server&timeout=30
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  # Redis (optional for caching and session management)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: